//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18010
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDManager_Dev4.FTPUsers {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FTPUsers.FTPUsersSoap")]
    public interface FTPUsersSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 glytm 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Admin", ReplyAction="*")]
        CDManager_Dev4.FTPUsers.AdminResponse Admin(CDManager_Dev4.FTPUsers.AdminRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 GetMaxUserResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMaxUser", ReplyAction="*")]
        CDManager_Dev4.FTPUsers.GetMaxUserResponse GetMaxUser(CDManager_Dev4.FTPUsers.GetMaxUserRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 user 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetMaxUser", ReplyAction="*")]
        CDManager_Dev4.FTPUsers.SetMaxUserResponse SetMaxUser(CDManager_Dev4.FTPUsers.SetMaxUserRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 glytm 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdatePasswd", ReplyAction="*")]
        CDManager_Dev4.FTPUsers.UpdatePasswdResponse UpdatePasswd(CDManager_Dev4.FTPUsers.UpdatePasswdRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 glytm 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NewUser", ReplyAction="*")]
        CDManager_Dev4.FTPUsers.NewUserResponse NewUser(CDManager_Dev4.FTPUsers.NewUserRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 glytm 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteUser", ReplyAction="*")]
        CDManager_Dev4.FTPUsers.DeleteUserResponse DeleteUser(CDManager_Dev4.FTPUsers.DeleteUserRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AdminRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Admin", Namespace="http://tempuri.org/", Order=0)]
        public CDManager_Dev4.FTPUsers.AdminRequestBody Body;
        
        public AdminRequest() {
        }
        
        public AdminRequest(CDManager_Dev4.FTPUsers.AdminRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AdminRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string glytm;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mm;
        
        public AdminRequestBody() {
        }
        
        public AdminRequestBody(string glytm, string mm) {
            this.glytm = glytm;
            this.mm = mm;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AdminResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AdminResponse", Namespace="http://tempuri.org/", Order=0)]
        public CDManager_Dev4.FTPUsers.AdminResponseBody Body;
        
        public AdminResponse() {
        }
        
        public AdminResponse(CDManager_Dev4.FTPUsers.AdminResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AdminResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AdminResult;
        
        public AdminResponseBody() {
        }
        
        public AdminResponseBody(bool AdminResult) {
            this.AdminResult = AdminResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMaxUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMaxUser", Namespace="http://tempuri.org/", Order=0)]
        public CDManager_Dev4.FTPUsers.GetMaxUserRequestBody Body;
        
        public GetMaxUserRequest() {
        }
        
        public GetMaxUserRequest(CDManager_Dev4.FTPUsers.GetMaxUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetMaxUserRequestBody {
        
        public GetMaxUserRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMaxUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMaxUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public CDManager_Dev4.FTPUsers.GetMaxUserResponseBody Body;
        
        public GetMaxUserResponse() {
        }
        
        public GetMaxUserResponse(CDManager_Dev4.FTPUsers.GetMaxUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMaxUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetMaxUserResult;
        
        public GetMaxUserResponseBody() {
        }
        
        public GetMaxUserResponseBody(string GetMaxUserResult) {
            this.GetMaxUserResult = GetMaxUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetMaxUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetMaxUser", Namespace="http://tempuri.org/", Order=0)]
        public CDManager_Dev4.FTPUsers.SetMaxUserRequestBody Body;
        
        public SetMaxUserRequest() {
        }
        
        public SetMaxUserRequest(CDManager_Dev4.FTPUsers.SetMaxUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetMaxUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string new_max;
        
        public SetMaxUserRequestBody() {
        }
        
        public SetMaxUserRequestBody(string user, string new_max) {
            this.user = user;
            this.new_max = new_max;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetMaxUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetMaxUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public CDManager_Dev4.FTPUsers.SetMaxUserResponseBody Body;
        
        public SetMaxUserResponse() {
        }
        
        public SetMaxUserResponse(CDManager_Dev4.FTPUsers.SetMaxUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetMaxUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SetMaxUserResult;
        
        public SetMaxUserResponseBody() {
        }
        
        public SetMaxUserResponseBody(bool SetMaxUserResult) {
            this.SetMaxUserResult = SetMaxUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdatePasswdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdatePasswd", Namespace="http://tempuri.org/", Order=0)]
        public CDManager_Dev4.FTPUsers.UpdatePasswdRequestBody Body;
        
        public UpdatePasswdRequest() {
        }
        
        public UpdatePasswdRequest(CDManager_Dev4.FTPUsers.UpdatePasswdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdatePasswdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string glytm;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mm;
        
        public UpdatePasswdRequestBody() {
        }
        
        public UpdatePasswdRequestBody(string glytm, string mm) {
            this.glytm = glytm;
            this.mm = mm;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdatePasswdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdatePasswdResponse", Namespace="http://tempuri.org/", Order=0)]
        public CDManager_Dev4.FTPUsers.UpdatePasswdResponseBody Body;
        
        public UpdatePasswdResponse() {
        }
        
        public UpdatePasswdResponse(CDManager_Dev4.FTPUsers.UpdatePasswdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdatePasswdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdatePasswdResult;
        
        public UpdatePasswdResponseBody() {
        }
        
        public UpdatePasswdResponseBody(bool UpdatePasswdResult) {
            this.UpdatePasswdResult = UpdatePasswdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NewUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NewUser", Namespace="http://tempuri.org/", Order=0)]
        public CDManager_Dev4.FTPUsers.NewUserRequestBody Body;
        
        public NewUserRequest() {
        }
        
        public NewUserRequest(CDManager_Dev4.FTPUsers.NewUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NewUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string glytm;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mm;
        
        public NewUserRequestBody() {
        }
        
        public NewUserRequestBody(string glytm, string mm) {
            this.glytm = glytm;
            this.mm = mm;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NewUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NewUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public CDManager_Dev4.FTPUsers.NewUserResponseBody Body;
        
        public NewUserResponse() {
        }
        
        public NewUserResponse(CDManager_Dev4.FTPUsers.NewUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NewUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool NewUserResult;
        
        public NewUserResponseBody() {
        }
        
        public NewUserResponseBody(bool NewUserResult) {
            this.NewUserResult = NewUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteUser", Namespace="http://tempuri.org/", Order=0)]
        public CDManager_Dev4.FTPUsers.DeleteUserRequestBody Body;
        
        public DeleteUserRequest() {
        }
        
        public DeleteUserRequest(CDManager_Dev4.FTPUsers.DeleteUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string glytm;
        
        public DeleteUserRequestBody() {
        }
        
        public DeleteUserRequestBody(string glytm) {
            this.glytm = glytm;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public CDManager_Dev4.FTPUsers.DeleteUserResponseBody Body;
        
        public DeleteUserResponse() {
        }
        
        public DeleteUserResponse(CDManager_Dev4.FTPUsers.DeleteUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool DeleteUserResult;
        
        public DeleteUserResponseBody() {
        }
        
        public DeleteUserResponseBody(bool DeleteUserResult) {
            this.DeleteUserResult = DeleteUserResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FTPUsersSoapChannel : CDManager_Dev4.FTPUsers.FTPUsersSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FTPUsersSoapClient : System.ServiceModel.ClientBase<CDManager_Dev4.FTPUsers.FTPUsersSoap>, CDManager_Dev4.FTPUsers.FTPUsersSoap {
        
        public FTPUsersSoapClient() {
        }
        
        public FTPUsersSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FTPUsersSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FTPUsersSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FTPUsersSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CDManager_Dev4.FTPUsers.AdminResponse CDManager_Dev4.FTPUsers.FTPUsersSoap.Admin(CDManager_Dev4.FTPUsers.AdminRequest request) {
            return base.Channel.Admin(request);
        }
        
        public bool Admin(string glytm, string mm) {
            CDManager_Dev4.FTPUsers.AdminRequest inValue = new CDManager_Dev4.FTPUsers.AdminRequest();
            inValue.Body = new CDManager_Dev4.FTPUsers.AdminRequestBody();
            inValue.Body.glytm = glytm;
            inValue.Body.mm = mm;
            CDManager_Dev4.FTPUsers.AdminResponse retVal = ((CDManager_Dev4.FTPUsers.FTPUsersSoap)(this)).Admin(inValue);
            return retVal.Body.AdminResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CDManager_Dev4.FTPUsers.GetMaxUserResponse CDManager_Dev4.FTPUsers.FTPUsersSoap.GetMaxUser(CDManager_Dev4.FTPUsers.GetMaxUserRequest request) {
            return base.Channel.GetMaxUser(request);
        }
        
        public string GetMaxUser() {
            CDManager_Dev4.FTPUsers.GetMaxUserRequest inValue = new CDManager_Dev4.FTPUsers.GetMaxUserRequest();
            inValue.Body = new CDManager_Dev4.FTPUsers.GetMaxUserRequestBody();
            CDManager_Dev4.FTPUsers.GetMaxUserResponse retVal = ((CDManager_Dev4.FTPUsers.FTPUsersSoap)(this)).GetMaxUser(inValue);
            return retVal.Body.GetMaxUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CDManager_Dev4.FTPUsers.SetMaxUserResponse CDManager_Dev4.FTPUsers.FTPUsersSoap.SetMaxUser(CDManager_Dev4.FTPUsers.SetMaxUserRequest request) {
            return base.Channel.SetMaxUser(request);
        }
        
        public bool SetMaxUser(string user, string new_max) {
            CDManager_Dev4.FTPUsers.SetMaxUserRequest inValue = new CDManager_Dev4.FTPUsers.SetMaxUserRequest();
            inValue.Body = new CDManager_Dev4.FTPUsers.SetMaxUserRequestBody();
            inValue.Body.user = user;
            inValue.Body.new_max = new_max;
            CDManager_Dev4.FTPUsers.SetMaxUserResponse retVal = ((CDManager_Dev4.FTPUsers.FTPUsersSoap)(this)).SetMaxUser(inValue);
            return retVal.Body.SetMaxUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CDManager_Dev4.FTPUsers.UpdatePasswdResponse CDManager_Dev4.FTPUsers.FTPUsersSoap.UpdatePasswd(CDManager_Dev4.FTPUsers.UpdatePasswdRequest request) {
            return base.Channel.UpdatePasswd(request);
        }
        
        public bool UpdatePasswd(string glytm, string mm) {
            CDManager_Dev4.FTPUsers.UpdatePasswdRequest inValue = new CDManager_Dev4.FTPUsers.UpdatePasswdRequest();
            inValue.Body = new CDManager_Dev4.FTPUsers.UpdatePasswdRequestBody();
            inValue.Body.glytm = glytm;
            inValue.Body.mm = mm;
            CDManager_Dev4.FTPUsers.UpdatePasswdResponse retVal = ((CDManager_Dev4.FTPUsers.FTPUsersSoap)(this)).UpdatePasswd(inValue);
            return retVal.Body.UpdatePasswdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CDManager_Dev4.FTPUsers.NewUserResponse CDManager_Dev4.FTPUsers.FTPUsersSoap.NewUser(CDManager_Dev4.FTPUsers.NewUserRequest request) {
            return base.Channel.NewUser(request);
        }
        
        public bool NewUser(string glytm, string mm) {
            CDManager_Dev4.FTPUsers.NewUserRequest inValue = new CDManager_Dev4.FTPUsers.NewUserRequest();
            inValue.Body = new CDManager_Dev4.FTPUsers.NewUserRequestBody();
            inValue.Body.glytm = glytm;
            inValue.Body.mm = mm;
            CDManager_Dev4.FTPUsers.NewUserResponse retVal = ((CDManager_Dev4.FTPUsers.FTPUsersSoap)(this)).NewUser(inValue);
            return retVal.Body.NewUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CDManager_Dev4.FTPUsers.DeleteUserResponse CDManager_Dev4.FTPUsers.FTPUsersSoap.DeleteUser(CDManager_Dev4.FTPUsers.DeleteUserRequest request) {
            return base.Channel.DeleteUser(request);
        }
        
        public bool DeleteUser(string glytm) {
            CDManager_Dev4.FTPUsers.DeleteUserRequest inValue = new CDManager_Dev4.FTPUsers.DeleteUserRequest();
            inValue.Body = new CDManager_Dev4.FTPUsers.DeleteUserRequestBody();
            inValue.Body.glytm = glytm;
            CDManager_Dev4.FTPUsers.DeleteUserResponse retVal = ((CDManager_Dev4.FTPUsers.FTPUsersSoap)(this)).DeleteUser(inValue);
            return retVal.Body.DeleteUserResult;
        }
    }
}
