//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDManager_Dev4.CDFile {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CDFile.CDFileSoap")]
    public interface CDFileSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 glytm 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFile", ReplyAction="*")]
        CDManager_Dev4.CDFile.GetFileResponse GetFile(CDManager_Dev4.CDFile.GetFileRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 glytm 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveFile", ReplyAction="*")]
        CDManager_Dev4.CDFile.RemoveFileResponse RemoveFile(CDManager_Dev4.CDFile.RemoveFileRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 glytm 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadConfirm", ReplyAction="*")]
        CDManager_Dev4.CDFile.UploadConfirmResponse UploadConfirm(CDManager_Dev4.CDFile.UploadConfirmRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 isbn 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateFileName", ReplyAction="*")]
        CDManager_Dev4.CDFile.UpdateFileNameResponse UpdateFileName(CDManager_Dev4.CDFile.UpdateFileNameRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 isbn 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFileName", ReplyAction="*")]
        CDManager_Dev4.CDFile.GetFileNameResponse GetFileName(CDManager_Dev4.CDFile.GetFileNameRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 glytm 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUploadedFiles", ReplyAction="*")]
        CDManager_Dev4.CDFile.GetUploadedFilesResponse GetUploadedFiles(CDManager_Dev4.CDFile.GetUploadedFilesRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 glytm 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveUploadedFile", ReplyAction="*")]
        CDManager_Dev4.CDFile.RemoveUploadedFileResponse RemoveUploadedFile(CDManager_Dev4.CDFile.RemoveUploadedFileRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 glytm 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateUploadedFile", ReplyAction="*")]
        CDManager_Dev4.CDFile.UpdateUploadedFileResponse UpdateUploadedFile(CDManager_Dev4.CDFile.UpdateUploadedFileRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFile", Namespace="http://tempuri.org/", Order=0)]
        public CDManager_Dev4.CDFile.GetFileRequestBody Body;
        
        public GetFileRequest() {
        }
        
        public GetFileRequest(CDManager_Dev4.CDFile.GetFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string glytm;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string isbn;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ztm;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string cdxh;
        
        public GetFileRequestBody() {
        }
        
        public GetFileRequestBody(string glytm, string isbn, string ztm, string cdxh) {
            this.glytm = glytm;
            this.isbn = isbn;
            this.ztm = ztm;
            this.cdxh = cdxh;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileResponse", Namespace="http://tempuri.org/", Order=0)]
        public CDManager_Dev4.CDFile.GetFileResponseBody Body;
        
        public GetFileResponse() {
        }
        
        public GetFileResponse(CDManager_Dev4.CDFile.GetFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetFileResult;
        
        public GetFileResponseBody() {
        }
        
        public GetFileResponseBody(string GetFileResult) {
            this.GetFileResult = GetFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveFile", Namespace="http://tempuri.org/", Order=0)]
        public CDManager_Dev4.CDFile.RemoveFileRequestBody Body;
        
        public RemoveFileRequest() {
        }
        
        public RemoveFileRequest(CDManager_Dev4.CDFile.RemoveFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RemoveFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string glytm;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string isbn;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ztm;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string cdxh;
        
        public RemoveFileRequestBody() {
        }
        
        public RemoveFileRequestBody(string glytm, string isbn, string ztm, string cdxh) {
            this.glytm = glytm;
            this.isbn = isbn;
            this.ztm = ztm;
            this.cdxh = cdxh;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveFileResponse", Namespace="http://tempuri.org/", Order=0)]
        public CDManager_Dev4.CDFile.RemoveFileResponseBody Body;
        
        public RemoveFileResponse() {
        }
        
        public RemoveFileResponse(CDManager_Dev4.CDFile.RemoveFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RemoveFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool RemoveFileResult;
        
        public RemoveFileResponseBody() {
        }
        
        public RemoveFileResponseBody(bool RemoveFileResult) {
            this.RemoveFileResult = RemoveFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadConfirmRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadConfirm", Namespace="http://tempuri.org/", Order=0)]
        public CDManager_Dev4.CDFile.UploadConfirmRequestBody Body;
        
        public UploadConfirmRequest() {
        }
        
        public UploadConfirmRequest(CDManager_Dev4.CDFile.UploadConfirmRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadConfirmRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string glytm;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string isbn;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ztm;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string cdxh;
        
        public UploadConfirmRequestBody() {
        }
        
        public UploadConfirmRequestBody(string glytm, string isbn, string ztm, string cdxh) {
            this.glytm = glytm;
            this.isbn = isbn;
            this.ztm = ztm;
            this.cdxh = cdxh;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadConfirmResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadConfirmResponse", Namespace="http://tempuri.org/", Order=0)]
        public CDManager_Dev4.CDFile.UploadConfirmResponseBody Body;
        
        public UploadConfirmResponse() {
        }
        
        public UploadConfirmResponse(CDManager_Dev4.CDFile.UploadConfirmResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadConfirmResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UploadConfirmResult;
        
        public UploadConfirmResponseBody() {
        }
        
        public UploadConfirmResponseBody(string UploadConfirmResult) {
            this.UploadConfirmResult = UploadConfirmResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateFileNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateFileName", Namespace="http://tempuri.org/", Order=0)]
        public CDManager_Dev4.CDFile.UpdateFileNameRequestBody Body;
        
        public UpdateFileNameRequest() {
        }
        
        public UpdateFileNameRequest(CDManager_Dev4.CDFile.UpdateFileNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateFileNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string isbn;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ztm;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string cdxh;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string cdmc;
        
        public UpdateFileNameRequestBody() {
        }
        
        public UpdateFileNameRequestBody(string isbn, string ztm, string cdxh, string cdmc) {
            this.isbn = isbn;
            this.ztm = ztm;
            this.cdxh = cdxh;
            this.cdmc = cdmc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateFileNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateFileNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public CDManager_Dev4.CDFile.UpdateFileNameResponseBody Body;
        
        public UpdateFileNameResponse() {
        }
        
        public UpdateFileNameResponse(CDManager_Dev4.CDFile.UpdateFileNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateFileNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateFileNameResult;
        
        public UpdateFileNameResponseBody() {
        }
        
        public UpdateFileNameResponseBody(bool UpdateFileNameResult) {
            this.UpdateFileNameResult = UpdateFileNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileName", Namespace="http://tempuri.org/", Order=0)]
        public CDManager_Dev4.CDFile.GetFileNameRequestBody Body;
        
        public GetFileNameRequest() {
        }
        
        public GetFileNameRequest(CDManager_Dev4.CDFile.GetFileNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFileNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string isbn;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ztm;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string cdxh;
        
        public GetFileNameRequestBody() {
        }
        
        public GetFileNameRequestBody(string isbn, string ztm, string cdxh) {
            this.isbn = isbn;
            this.ztm = ztm;
            this.cdxh = cdxh;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public CDManager_Dev4.CDFile.GetFileNameResponseBody Body;
        
        public GetFileNameResponse() {
        }
        
        public GetFileNameResponse(CDManager_Dev4.CDFile.GetFileNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFileNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetFileNameResult;
        
        public GetFileNameResponseBody() {
        }
        
        public GetFileNameResponseBody(string GetFileNameResult) {
            this.GetFileNameResult = GetFileNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUploadedFilesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUploadedFiles", Namespace="http://tempuri.org/", Order=0)]
        public CDManager_Dev4.CDFile.GetUploadedFilesRequestBody Body;
        
        public GetUploadedFilesRequest() {
        }
        
        public GetUploadedFilesRequest(CDManager_Dev4.CDFile.GetUploadedFilesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUploadedFilesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string glytm;
        
        public GetUploadedFilesRequestBody() {
        }
        
        public GetUploadedFilesRequestBody(string glytm) {
            this.glytm = glytm;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUploadedFilesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUploadedFilesResponse", Namespace="http://tempuri.org/", Order=0)]
        public CDManager_Dev4.CDFile.GetUploadedFilesResponseBody Body;
        
        public GetUploadedFilesResponse() {
        }
        
        public GetUploadedFilesResponse(CDManager_Dev4.CDFile.GetUploadedFilesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUploadedFilesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CDManager_Dev4.CDFile.ArrayOfString GetUploadedFilesResult;
        
        public GetUploadedFilesResponseBody() {
        }
        
        public GetUploadedFilesResponseBody(CDManager_Dev4.CDFile.ArrayOfString GetUploadedFilesResult) {
            this.GetUploadedFilesResult = GetUploadedFilesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveUploadedFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveUploadedFile", Namespace="http://tempuri.org/", Order=0)]
        public CDManager_Dev4.CDFile.RemoveUploadedFileRequestBody Body;
        
        public RemoveUploadedFileRequest() {
        }
        
        public RemoveUploadedFileRequest(CDManager_Dev4.CDFile.RemoveUploadedFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RemoveUploadedFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string glytm;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        public RemoveUploadedFileRequestBody() {
        }
        
        public RemoveUploadedFileRequestBody(string glytm, string name) {
            this.glytm = glytm;
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveUploadedFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveUploadedFileResponse", Namespace="http://tempuri.org/", Order=0)]
        public CDManager_Dev4.CDFile.RemoveUploadedFileResponseBody Body;
        
        public RemoveUploadedFileResponse() {
        }
        
        public RemoveUploadedFileResponse(CDManager_Dev4.CDFile.RemoveUploadedFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RemoveUploadedFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool RemoveUploadedFileResult;
        
        public RemoveUploadedFileResponseBody() {
        }
        
        public RemoveUploadedFileResponseBody(bool RemoveUploadedFileResult) {
            this.RemoveUploadedFileResult = RemoveUploadedFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUploadedFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUploadedFile", Namespace="http://tempuri.org/", Order=0)]
        public CDManager_Dev4.CDFile.UpdateUploadedFileRequestBody Body;
        
        public UpdateUploadedFileRequest() {
        }
        
        public UpdateUploadedFileRequest(CDManager_Dev4.CDFile.UpdateUploadedFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateUploadedFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string glytm;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string newName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ext;
        
        public UpdateUploadedFileRequestBody() {
        }
        
        public UpdateUploadedFileRequestBody(string glytm, string name, string newName, string ext) {
            this.glytm = glytm;
            this.name = name;
            this.newName = newName;
            this.ext = ext;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUploadedFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUploadedFileResponse", Namespace="http://tempuri.org/", Order=0)]
        public CDManager_Dev4.CDFile.UpdateUploadedFileResponseBody Body;
        
        public UpdateUploadedFileResponse() {
        }
        
        public UpdateUploadedFileResponse(CDManager_Dev4.CDFile.UpdateUploadedFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateUploadedFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateUploadedFileResult;
        
        public UpdateUploadedFileResponseBody() {
        }
        
        public UpdateUploadedFileResponseBody(bool UpdateUploadedFileResult) {
            this.UpdateUploadedFileResult = UpdateUploadedFileResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CDFileSoapChannel : CDManager_Dev4.CDFile.CDFileSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CDFileSoapClient : System.ServiceModel.ClientBase<CDManager_Dev4.CDFile.CDFileSoap>, CDManager_Dev4.CDFile.CDFileSoap {
        
        public CDFileSoapClient() {
        }
        
        public CDFileSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CDFileSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CDFileSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CDFileSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CDManager_Dev4.CDFile.GetFileResponse CDManager_Dev4.CDFile.CDFileSoap.GetFile(CDManager_Dev4.CDFile.GetFileRequest request) {
            return base.Channel.GetFile(request);
        }
        
        public string GetFile(string glytm, string isbn, string ztm, string cdxh) {
            CDManager_Dev4.CDFile.GetFileRequest inValue = new CDManager_Dev4.CDFile.GetFileRequest();
            inValue.Body = new CDManager_Dev4.CDFile.GetFileRequestBody();
            inValue.Body.glytm = glytm;
            inValue.Body.isbn = isbn;
            inValue.Body.ztm = ztm;
            inValue.Body.cdxh = cdxh;
            CDManager_Dev4.CDFile.GetFileResponse retVal = ((CDManager_Dev4.CDFile.CDFileSoap)(this)).GetFile(inValue);
            return retVal.Body.GetFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CDManager_Dev4.CDFile.RemoveFileResponse CDManager_Dev4.CDFile.CDFileSoap.RemoveFile(CDManager_Dev4.CDFile.RemoveFileRequest request) {
            return base.Channel.RemoveFile(request);
        }
        
        public bool RemoveFile(string glytm, string isbn, string ztm, string cdxh) {
            CDManager_Dev4.CDFile.RemoveFileRequest inValue = new CDManager_Dev4.CDFile.RemoveFileRequest();
            inValue.Body = new CDManager_Dev4.CDFile.RemoveFileRequestBody();
            inValue.Body.glytm = glytm;
            inValue.Body.isbn = isbn;
            inValue.Body.ztm = ztm;
            inValue.Body.cdxh = cdxh;
            CDManager_Dev4.CDFile.RemoveFileResponse retVal = ((CDManager_Dev4.CDFile.CDFileSoap)(this)).RemoveFile(inValue);
            return retVal.Body.RemoveFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CDManager_Dev4.CDFile.UploadConfirmResponse CDManager_Dev4.CDFile.CDFileSoap.UploadConfirm(CDManager_Dev4.CDFile.UploadConfirmRequest request) {
            return base.Channel.UploadConfirm(request);
        }
        
        public string UploadConfirm(string glytm, string isbn, string ztm, string cdxh) {
            CDManager_Dev4.CDFile.UploadConfirmRequest inValue = new CDManager_Dev4.CDFile.UploadConfirmRequest();
            inValue.Body = new CDManager_Dev4.CDFile.UploadConfirmRequestBody();
            inValue.Body.glytm = glytm;
            inValue.Body.isbn = isbn;
            inValue.Body.ztm = ztm;
            inValue.Body.cdxh = cdxh;
            CDManager_Dev4.CDFile.UploadConfirmResponse retVal = ((CDManager_Dev4.CDFile.CDFileSoap)(this)).UploadConfirm(inValue);
            return retVal.Body.UploadConfirmResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CDManager_Dev4.CDFile.UpdateFileNameResponse CDManager_Dev4.CDFile.CDFileSoap.UpdateFileName(CDManager_Dev4.CDFile.UpdateFileNameRequest request) {
            return base.Channel.UpdateFileName(request);
        }
        
        public bool UpdateFileName(string isbn, string ztm, string cdxh, string cdmc) {
            CDManager_Dev4.CDFile.UpdateFileNameRequest inValue = new CDManager_Dev4.CDFile.UpdateFileNameRequest();
            inValue.Body = new CDManager_Dev4.CDFile.UpdateFileNameRequestBody();
            inValue.Body.isbn = isbn;
            inValue.Body.ztm = ztm;
            inValue.Body.cdxh = cdxh;
            inValue.Body.cdmc = cdmc;
            CDManager_Dev4.CDFile.UpdateFileNameResponse retVal = ((CDManager_Dev4.CDFile.CDFileSoap)(this)).UpdateFileName(inValue);
            return retVal.Body.UpdateFileNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CDManager_Dev4.CDFile.GetFileNameResponse CDManager_Dev4.CDFile.CDFileSoap.GetFileName(CDManager_Dev4.CDFile.GetFileNameRequest request) {
            return base.Channel.GetFileName(request);
        }
        
        public string GetFileName(string isbn, string ztm, string cdxh) {
            CDManager_Dev4.CDFile.GetFileNameRequest inValue = new CDManager_Dev4.CDFile.GetFileNameRequest();
            inValue.Body = new CDManager_Dev4.CDFile.GetFileNameRequestBody();
            inValue.Body.isbn = isbn;
            inValue.Body.ztm = ztm;
            inValue.Body.cdxh = cdxh;
            CDManager_Dev4.CDFile.GetFileNameResponse retVal = ((CDManager_Dev4.CDFile.CDFileSoap)(this)).GetFileName(inValue);
            return retVal.Body.GetFileNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CDManager_Dev4.CDFile.GetUploadedFilesResponse CDManager_Dev4.CDFile.CDFileSoap.GetUploadedFiles(CDManager_Dev4.CDFile.GetUploadedFilesRequest request) {
            return base.Channel.GetUploadedFiles(request);
        }
        
        public CDManager_Dev4.CDFile.ArrayOfString GetUploadedFiles(string glytm) {
            CDManager_Dev4.CDFile.GetUploadedFilesRequest inValue = new CDManager_Dev4.CDFile.GetUploadedFilesRequest();
            inValue.Body = new CDManager_Dev4.CDFile.GetUploadedFilesRequestBody();
            inValue.Body.glytm = glytm;
            CDManager_Dev4.CDFile.GetUploadedFilesResponse retVal = ((CDManager_Dev4.CDFile.CDFileSoap)(this)).GetUploadedFiles(inValue);
            return retVal.Body.GetUploadedFilesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CDManager_Dev4.CDFile.RemoveUploadedFileResponse CDManager_Dev4.CDFile.CDFileSoap.RemoveUploadedFile(CDManager_Dev4.CDFile.RemoveUploadedFileRequest request) {
            return base.Channel.RemoveUploadedFile(request);
        }
        
        public bool RemoveUploadedFile(string glytm, string name) {
            CDManager_Dev4.CDFile.RemoveUploadedFileRequest inValue = new CDManager_Dev4.CDFile.RemoveUploadedFileRequest();
            inValue.Body = new CDManager_Dev4.CDFile.RemoveUploadedFileRequestBody();
            inValue.Body.glytm = glytm;
            inValue.Body.name = name;
            CDManager_Dev4.CDFile.RemoveUploadedFileResponse retVal = ((CDManager_Dev4.CDFile.CDFileSoap)(this)).RemoveUploadedFile(inValue);
            return retVal.Body.RemoveUploadedFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CDManager_Dev4.CDFile.UpdateUploadedFileResponse CDManager_Dev4.CDFile.CDFileSoap.UpdateUploadedFile(CDManager_Dev4.CDFile.UpdateUploadedFileRequest request) {
            return base.Channel.UpdateUploadedFile(request);
        }
        
        public bool UpdateUploadedFile(string glytm, string name, string newName, string ext) {
            CDManager_Dev4.CDFile.UpdateUploadedFileRequest inValue = new CDManager_Dev4.CDFile.UpdateUploadedFileRequest();
            inValue.Body = new CDManager_Dev4.CDFile.UpdateUploadedFileRequestBody();
            inValue.Body.glytm = glytm;
            inValue.Body.name = name;
            inValue.Body.newName = newName;
            inValue.Body.ext = ext;
            CDManager_Dev4.CDFile.UpdateUploadedFileResponse retVal = ((CDManager_Dev4.CDFile.CDFileSoap)(this)).UpdateUploadedFile(inValue);
            return retVal.Body.UpdateUploadedFileResult;
        }
    }
}
