//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18010
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDManager_Dev4.FTPDownloadFloder {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FTPDownloadFloder.FTPDownloadFloderSoap")]
    public interface FTPDownloadFloderSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Check", ReplyAction="*")]
        bool Check();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FTPDownloadFloderSoapChannel : CDManager_Dev4.FTPDownloadFloder.FTPDownloadFloderSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FTPDownloadFloderSoapClient : System.ServiceModel.ClientBase<CDManager_Dev4.FTPDownloadFloder.FTPDownloadFloderSoap>, CDManager_Dev4.FTPDownloadFloder.FTPDownloadFloderSoap {
        
        public FTPDownloadFloderSoapClient() {
        }
        
        public FTPDownloadFloderSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FTPDownloadFloderSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FTPDownloadFloderSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FTPDownloadFloderSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Check() {
            return base.Channel.Check();
        }
    }
}
