//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDManagerLibrary.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public Admin()
        {
            this.BanIP = new HashSet<BanIP>();
            this.Notice = new HashSet<Notice>();
            this.UploadLog = new HashSet<UploadLog>();
        }
    
        public string GLYTM { get; set; }
        public string XM { get; set; }
        public string MM { get; set; }
        public string XB { get; set; }
        public string YJDW { get; set; }
        public string EJDW { get; set; }
        public Nullable<System.DateTime> BZRQ { get; set; }
        public Nullable<System.DateTime> YXRQ { get; set; }
        public string YY { get; set; }
        public int GLYLX { get; set; }
        public Nullable<System.DateTime> FFSJ { get; set; }
        public string FFCZY { get; set; }
        public Nullable<int> YHZT { get; set; }
        public string MAC { get; set; }
        public string SCIP { get; set; }
        public Nullable<System.DateTime> SCRQ { get; set; }
    
        public virtual ICollection<BanIP> BanIP { get; set; }
        public virtual ICollection<Notice> Notice { get; set; }
        public virtual ICollection<UploadLog> UploadLog { get; set; }
    }
}
