//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDManagerLibrary.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public Book()
        {
            this.ApplyLog = new HashSet<ApplyLog>();
            this.CD = new HashSet<CD>();
        }
    
        public string ISBN { get; set; }
        public string ZTM { get; set; }
        public Nullable<decimal> DJ { get; set; }
        public string ZRZ { get; set; }
        public string CBS { get; set; }
        public string YEMA { get; set; }
        public string YSBMY { get; set; }
        public string KB { get; set; }
        public string FLTM { get; set; }
        public Nullable<System.DateTime> FFSJ { get; set; }
        public string FFCZY { get; set; }
    
        public virtual ICollection<ApplyLog> ApplyLog { get; set; }
        public virtual ICollection<CD> CD { get; set; }
    }
}
