//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDManagerLibrary.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CD
    {
        public CD()
        {
            this.DownloadLog = new HashSet<DownloadLog>();
            this.UploadLog = new HashSet<UploadLog>();
        }
    
        public long CDID { get; set; }
        public long BookID { get; set; }
        public string CDXH { get; set; }
        public string CDMC { get; set; }
        public string CDGS { get; set; }
        public Nullable<double> CDDX { get; set; }
        public string CDLJ { get; set; }
        public Nullable<int> ZXZT { get; set; }
        public Nullable<System.DateTime> CZSJ { get; set; }
        public string CZCZY { get; set; }
        public Nullable<System.DateTime> FFSJ { get; set; }
        public string FFCZY { get; set; }
        public string BZ { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual ICollection<DownloadLog> DownloadLog { get; set; }
        public virtual ICollection<UploadLog> UploadLog { get; set; }
    }
}
