//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDManagerLibrary.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CDManagerDevEntities : DbContext
    {
        public CDManagerDevEntities()
            : base("name=CDManagerDevEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Admin> Admin { get; set; }
        public DbSet<ApplyLog> ApplyLog { get; set; }
        public DbSet<BanIP> BanIP { get; set; }
        public DbSet<Book> Book { get; set; }
        public DbSet<BookType> BookType { get; set; }
        public DbSet<CD> CD { get; set; }
        public DbSet<DownloadLog> DownloadLog { get; set; }
        public DbSet<Message> Message { get; set; }
        public DbSet<Notice> Notice { get; set; }
        public DbSet<Reader> Reader { get; set; }
        public DbSet<SystemLog> SystemLog { get; set; }
        public DbSet<UploadLog> UploadLog { get; set; }
    }
}
