//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDManagerLibrary.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class DownloadLog
    {
        public string XZBH { get; set; }
        public string CZYTM { get; set; }
        public Nullable<long> CDID { get; set; }
        public Nullable<System.DateTime> XZSJ { get; set; }
        public string BZ { get; set; }
        public string IP { get; set; }
    
        public virtual CD CD { get; set; }
    }
}
