//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDManagerLibrary.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public string XXTM { get; set; }
        public string YHLX { get; set; }
        public string SXRTM { get; set; }
        public string FSRTM { get; set; }
        public Nullable<System.DateTime> FSSJ { get; set; }
        public string XXNR { get; set; }
        public Nullable<bool> YD { get; set; }
    }
}
