//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDManagerLibrary.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reader
    {
        public Reader()
        {
            this.ApplyLog = new HashSet<ApplyLog>();
        }
    
        public string DZTM { get; set; }
        public string XM { get; set; }
        public string MM { get; set; }
        public string XB { get; set; }
        public string YJDW { get; set; }
        public string EJDW { get; set; }
        public Nullable<System.DateTime> BZRQ { get; set; }
        public Nullable<System.DateTime> YXRQ { get; set; }
        public Nullable<System.DateTime> KSSJ { get; set; }
        public Nullable<System.DateTime> JSSJ { get; set; }
        public string YY { get; set; }
        public string DZLX { get; set; }
        public string DWDM { get; set; }
        public Nullable<System.DateTime> FFSJ { get; set; }
        public string FFCZY { get; set; }
        public string JZCZY { get; set; }
        public Nullable<int> YHZT { get; set; }
        public string SCIP { get; set; }
        public Nullable<System.DateTime> SCRQ { get; set; }
    
        public virtual ICollection<ApplyLog> ApplyLog { get; set; }
    }
}
